- name: Microsoft Excel
- name: Microsoft Word
- name: Microsoft PowerPoint
- name: Microsoft Teams
- name: Google Docs
- name: Google Sheets
- name: Google Forms
- name: Google Slides
- name: Notion
- name: Canva
- name: draw.io